name: List Bundles

on:
  workflow_dispatch:

jobs:
  list_bundles:
    runs-on: ubuntu-latest
    steps:
    - name: install Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'

    - name: pull deployment-scripts repo
      uses: actions/checkout@v3
      with:
        repository: Civiconnect/deployment-scripts
        ref: v1
        token: ${{ secrets.GH_TOKEN }}
        path: './deployment_scripts'

    - name: install deps and run
      id: run_script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd ./deployment_scripts
        npm install
        node listBundles.js
