# Installs Postgres on the remote server and sets up the database for the Strapi app.
# Secrets:
# - GH_TOKEN: token for accessing deployment-scripts repo
# - HOST_USER: user for SSH access to instance. e.g. bitnami
# - HOST_IP: IP address of instance
# - PRIVATE_SSH_KEY: private key for SSH access to instance
# - DB_NAME: name of the database to create
# - DB_USER: name of the database user to create
# - DB_PASSWORD: password for the database user

name: Setup POSTGRESSQL

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      hostIP:
        description: 'IP address of instance'
        type: string
        required: false
      hostName:
        description: 'Name of instance user'
        type: string
        required: false

jobs:
  setup_postgres:
    runs-on: ubuntu-latest

    steps:
    - name: pull deployment-scripts repo
      uses: actions/checkout@v3
      with:
        repository: Civiconnect/deployment-scripts
        ref: v1
        token: ${{ secrets.GH_TOKEN }}
        path: './deployment_scripts'

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: setup-postgress.ansible.yml
        directory: ./deployment_scripts/ansible
        key: ${{secrets.PRIVATE_SSH_KEY}}
        inventory: |
          [remote]
          ${{ inputs.hostName || secrets.HOST_USER }}@${{ inputs.hostIP || secrets.HOST_IP }}
        options: |
          --extra-vars "{HOST: remote, INFISICAL_TOKEN_DEVELOPMENT_STRAPI: "${{ secrets.INFISICAL_TOKEN_DEVELOPMENT_STRAPI }}", INFISICAL_TOKEN_PRODUCTION_STRAPI: "${{ secrets.INFISICAL_TOKEN_PRODUCTION_STRAPI }}"}"
          --verbose
